package com.obrynex.studyguard.aitutor

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.obrynex.studyguard.ai.*
import com.obrynex.studyguard.debug.DebugAgentLog
import com.obrynex.studyguard.textrank.SummarizeWithTextRankUseCase
import kotlinx.coroutines.Job
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

data class ChatMessage(
    val text      : String,
    val isUser    : Boolean,
    val isLoading : Boolean = false,
    /** True when this message was generated by TextRank (fallback mode). */
    val isFallback: Boolean = false
)

data class AiTutorState(
    val messages      : List<ChatMessage> = emptyList(),
    val input         : String            = "",
    val subject       : String            = "",
    val isGenerating  : Boolean           = false,
    /** Mirrors [AIEngineManager.state] — single source of truth, never duplicated. */
    val modelState    : AIModelState      = AIModelState.Idle,
    /** Absolute path shown in setup instructions when model is missing. */
    val modelPath     : String            = "",
    /**
     * When true the engine entered a failed/closed state mid-session and the
     * VM automatically switched to the TextRank local summarizer as a fallback.
     */
    val isFallbackMode: Boolean           = false,
    /** Wall-clock ms from validate() start to Ready (mirrors [AIEngineManager.lastLoadTimeMs]). */
    val loadTimeMs    : Long              = -1L
) {
    val isModelReady  get() = modelState is AIModelState.Ready
    val isValidating  get() = modelState is AIModelState.Validating
                           || modelState is AIModelState.Loading
    /** True while the engine is initialising OR retrying — use to disable the Retry button. */
    val isRetrying    get() = modelState is AIModelState.Validating
                           || modelState is AIModelState.Loading
    val failureMessage get() = (modelState as? AIModelState.Failed)
                                    ?.reason?.toArabicMessage()
}

/**
 * One-shot UI events emitted to the screen via [events].
 * These are fire-and-forget signals that must not survive configuration changes.
 */
sealed class AiTutorEvent {
    /** A non-fatal inference error occurred — show a snackbar. */
    data class InferenceError(val message: String) : AiTutorEvent()
    /** Engine entered fallback mode automatically. */
    object FallbackActivated : AiTutorEvent()
}

/**
 * ViewModel for the AI Tutor screen.
 *
 * ### One-shot events
 * [events] is a [Channel]-backed flow. Each event is delivered exactly once —
 * it will not be re-delivered after screen rotation.
 *
 * ### Job management
 * [activeJob] tracks the current send/retry coroutine. Calling [retryEngine]
 * cancels any in-progress job before launching a new one, preventing races.
 *
 * ### Fallback mode
 * If inference fails mid-stream, [isFallbackMode] is set to true and subsequent
 * [send] calls use the TextRank local summarizer. The engine is re-initialised in
 * the background; once ready, fallback mode is cleared automatically.
 */
class AiTutorViewModel(
    private val manager   : AIEngineManager,
    private val textRank  : SummarizeWithTextRankUseCase = SummarizeWithTextRankUseCase()
) : ViewModel() {

    private val _state = MutableStateFlow(
        AiTutorState(modelPath = manager.modelFilePath)
    )
    val state: StateFlow<AiTutorState> = _state.asStateFlow()

    /**
     * Channel-backed one-shot event stream.
     * Collect exactly once in the Composable using [LaunchedEffect].
     */
    private val _events = Channel<AiTutorEvent>(Channel.BUFFERED)
    val events = _events.receiveAsFlow()

    /** Tracks the active send/engine-init job so it can be cancelled before a retry. */
    private var activeJob: Job? = null

    init {
        viewModelScope.launch {
            manager.state.collect { engineState ->
                _state.update { s ->
                    s.copy(
                        modelState   = engineState,
                        loadTimeMs   = manager.lastLoadTimeMs,
                        // If engine recovered from fallback mode → clear flag
                        isFallbackMode = if (engineState is AIModelState.Ready) false
                                         else s.isFallbackMode
                    )
                }
            }
        }
    }

    /**
     * Triggers model validation and warm-up.
     * Safe to call multiple times — [AIEngineManager.validate] is idempotent.
     */
    fun startEngine() {
        viewModelScope.launch { manager.validate() }
    }

    /**
     * Cancels any active job and re-initialises the engine.
     * The Retry button in the UI should be disabled while [AiTutorState.isRetrying].
     */
    fun retryEngine() {
        activeJob?.cancel()
        activeJob = viewModelScope.launch { manager.requestReInit() }
    }

    fun onInputChanged(text: String) = _state.update { it.copy(input = text) }
    fun onSubjectChanged(s: String)  = _state.update { it.copy(subject = s) }

    fun send() {
        val text = _state.value.input.trim().ifBlank { return }
        if (_state.value.isGenerating) return

        // Fallback path — TextRank summarizer (AI engine unavailable)
        if (_state.value.isFallbackMode) {
            sendFallback(text)
            return
        }

        val engine = manager.getEngine() ?: return

        val userMsg = ChatMessage(text, isUser = true)
        val loadMsg = ChatMessage("", isUser = false, isLoading = true)
        _state.update {
            it.copy(messages = it.messages + userMsg + loadMsg, input = "", isGenerating = true)
        }

        activeJob?.cancel()
        activeJob = viewModelScope.launch {
            var response = ""
            runCatching {
                engine.ask(text, _state.value.subject).collect { token ->
                    response += token
                    _state.update { s ->
                        s.copy(messages = s.messages.dropLast(1) + ChatMessage(response, isUser = false))
                    }
                }
            }.onFailure { ex ->
                AppLogger.e("AiTutorViewModel", "Inference failed mid-stream", ex)
                // #region agent log
                val msgCountBefore = _state.value.messages.size
                // #endregion
                // Remove loading placeholder so the chat does not show a stuck spinner
                _state.update { s ->
                    val trimmed = s.messages.dropLastWhile { !it.isUser && (it.isLoading || it.text.isEmpty()) }
                    s.copy(messages = trimmed, isGenerating = false)
                }
                // #region agent log
                DebugAgentLog.log(
                    location = "AiTutorViewModel.kt:send",
                    message = "Inference failed — cleaned loading message",
                    hypothesisId = "C",
                    data = mapOf(
                        "error" to (ex.message ?: "unknown"),
                        "messagesBefore" to msgCountBefore,
                        "messagesAfter" to _state.value.messages.size
                    )
                )
                // #endregion
                _events.trySend(AiTutorEvent.InferenceError(ex.message ?: "Unknown error"))
                activateFallback()
            }
            _state.update { it.copy(isGenerating = false) }
        }
    }

    /**
     * Sends a message using the TextRank local summarizer.
     * Called automatically when [isFallbackMode] is true.
     *
     * TextRank extracts the most central sentences from the user's input and
     * returns them as a compact summary — no internet or model file required.
     * The result is displayed with [isFallback] = true so the UI can show a
     * distinguishing badge.
     *
     * Once the engine recovers (background re-init completes), [isFallbackMode]
     * is cleared automatically and subsequent messages go through the AI path.
     */
    private fun sendFallback(text: String) {
        val extracted = textRank(text, topN = 3)
        val reply = ChatMessage(
            text       = "⚠️ وضع بديل — الذكاء الاصطناعي يُعاد تحميله.\n\n" +
                         "ملخص مستخرج من نصك:\n\n$extracted",
            isUser     = false,
            isFallback = true
        )
        val userMsg = ChatMessage(text, isUser = true)
        _state.update {
            it.copy(messages = it.messages + userMsg + reply, input = "")
        }
    }

    private fun activateFallback() {
        _state.update { it.copy(isFallbackMode = true) }
        _events.trySend(AiTutorEvent.FallbackActivated)
        // Re-init the engine in the background
        viewModelScope.launch { manager.requestReInit() }
    }

    fun clear() = _state.update { it.copy(messages = emptyList()) }

    override fun onCleared() {
        super.onCleared()
        manager.releaseEngine()
    }
}
